# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: adsanjana7@gmail.com
author_name: sanjana
contract_name: assignment
deployment_language: python
preset_name: starter
project_name: work

